### ISSUE TITLE
Public VOD request

### ISSUE THREAD

**Issue by GarlicAx** [MitchellHarrison/valorant-dashboard#36]
### Game ID

12, 1002

### Additional notes (optional)

Hey I wanted to use your dataset in one of my school assignments and I wanted to request access to 2 of the videos for my "justifying validity of data source" segment. I just want to compare the data recorded, to the data seen at the end of the game so if possible that would help a lot thanks.

**Comment by GarlicAx** [comment]
Sorry to comment twice, but can I also have access to vod 250, 500 and 750? I realised 2 would probably not be enough, sorry.

**Comment by MitchellHarrison** [comment]
I made 12, 250, 500, and 750 public! It's Valorant, so expect some foul language by teammates (and possibly myself, who knows haha). But they should all be available. I checked, and it looks like I check the scoreboard at the end of each game, so you should at least be able to see my kills, deaths, assists, rounds won, and rounds lost at the end of each video. Stuff like ACS, average damage delta, and a couple other variables aren't on that screen though. For that, you would have to visit [my tracker](https://tracker.gg/valorant/profile/riot/mitch%23rrpls/matches) and scroll allllllllllllll the way to the games you want to see. But that may be annoying for you. 

Either way, issue closed, and thanks for the interest in my data! They're also available on Kaggle [here](https://www.kaggle.com/datasets/mitchellharrison/my-first-1000-valorant-games/data).
